@startuml NoteClass
skinparam classAttributeIconSize 0
hide circle
class Note {
    - {static}logger : Logger
    - {static}DATE_FORMATTER : DateTimeFormatter
    - {static}ID_LENGTH : int = 8
    - {static}numberOfNotes : int

    - id : String
    - title : String
    - filename : String
    - body : String
    - createdAt : Instant
    - modifiedAt : Instant
    - pinned : boolean
    - archived : boolean
    - archiveName : String
    - logs : List<String>
    - tags : List<String>
    - outgoingLinks : HashSet<String>
    - incomingLinks : HashSet<String>

    + Note(id : String, title : String, filename : String, body : String, createdAt : Instant, modifiedAt : Instant)
    + Note(id : String, title : String, filename : String, body : String, createdAt : Instant, modifiedAt : Instant,
           pinned : boolean, archived : boolean, archiveName : String, tags : List<String>)

    + getId() : String
    + getTitle() : String
    + getFilename() : String
    + getBody() : String
    + getCreatedAt() : Instant
    + getModifiedAt() : Instant
    + isPinned() : boolean
    + isArchived() : boolean
    + isLinkedTo(noteId : String) : boolean
    + isLinkedBy(noteId : String) : boolean
    + getArchiveName() : String
    + getTags() : List<String>
    + getNumberOfNotes() : int
    + getOutgoingLinks() : HashSet<String>
    + getIncomingLinks() : HashSet<String>

    + setTitle(title : String) : void
    + setFilename(filename : String) : void
    + setBody(body : String) : void
    + setPinned(pinned : boolean) : void
    + setArchived(archived : boolean) : void
    + setArchiveName(archiveName : String) : void
    + addTag(tag : String) : void
    + removeTag(tag : String) : void
    + addOutgoingLink(noteId : String) : void
    + addIncomingLink(noteId : String) : void
    + removeOutgoingLink(noteId : String) : void
    + removeIncomingLink(noteId : String) : void
    + updateModifiedAt() : void
    + loadBody(body : String) : void
    + toString() : String
}
@enduml