@startuml NoteOrganisationCommands
skinparam classAttributeIconSize 0
hide circle
abstract class Command {
    + {abstract} execute(notes : ArrayList<Note>, tags : List<String>, ui : UI, storage : Storage) : void
    + isExit() : boolean
}

class FindNoteCommand
class ListNoteCommand
class PinNoteCommand

' Inheritance
FindNoteCommand -up-|> Command
PinNoteCommand -up-|> Command
ListNoteCommand -up-|> Command
@enduml