@startuml NoteClass
skinparam classAttributeIconSize 0
hide circle

class Note {
    - {static} logger : Logger
    - {static} DATE_FORMATTER : DateTimeFormatter
    - {static} ID_LENGTH : int = 8
    - {static} numberOfNotes : int

    - id : String
    - title : String
    - filename : String
    - body : String
    - createdAt : Instant
    - modifiedAt : Instant
    - pinned : boolean
    - archived : boolean
    - archiveName : String
    - tags : List<String>
    - outgoingLinks : HashSet<String>
    - incomingLinks : HashSet<String>

    + Note(id : String, title : String, filename : String, body : String, createdAt : Instant, modifiedAt : Instant)
    + Note(id : String, title : String, filename : String, body : String, createdAt : Instant, modifiedAt : Instant,
           pinned : boolean, archived : boolean, archiveName : String, tags : List<String>)

    + getCreatedAt() : Instant
    + getModifiedAt() : Instant
    + isLinkedTo(noteId : String) : boolean
    + isLinkedBy(noteId : String) : boolean
    + getTags() : List<String>
    + {static} getNumberOfNotes() : int
    + getOutgoingLinks() : HashSet<String>
    + getIncomingLinks() : HashSet<String>

    + addTag(tag : String) : void
    + removeTag(tag : String) : void
    + addOutgoingLink(noteId : String) : void
    + addIncomingLink(noteId : String) : void
    + removeOutgoingLink(noteId : String) : void
    + removeIncomingLink(noteId : String) : void
    + updateModifiedAt() : void
    + loadBody(body : String) : void
}
@enduml