@startuml TagCommands
skinparam classAttributeIconSize 0

abstract class Command {
    + abstract void execute(ArrayList<Note> notes, List<String> tags, UI ui, Storage storage) 
    + boolean isExit()
}

class DeleteTagFromNoteCommand
class DeleteTagGloballyCommand
class ListTagsGlobalCommand
class ListTagsSingleNoteCommand
class NewTagCommand
class RenameTagCommand
class TagNoteCommand

DeleteTagFromNoteCommand -down-> Command
DeleteTagGloballyCommand -down-> Command
ListTagsSingleNoteCommand -up-> Command
NewTagCommand -down-> Command
RenameTagCommand -up-> Command
TagNoteCommand -down-> Command
ListTagsGlobalCommand -up-> Command
@enduml