@startuml UIClass
skinparam classAttributeIconSize 0
hide circle

class UI {
    - {static} LINE : String
    - {static} LIST_INCOMING : String
    - {static} LIST_OUTGOING : String
    - scanner : Scanner

    + UI()
    + readCommand() : String
    + showWelcome() : void
    + showHelp() : void
    + showDeletionCancelled() : void
    + showNoteDeleted(id : String) : void
    + showDeleteNoteConfirmation(id : String, noteTitle : String) : void
    + showDeleteTagConfirmation(tag : String) : void
    + showDeleteTagFromNoteConfirmation(tag : String, noteId : String) : void
    + showError(message : String) : void
    + showBye() : void
    + showAddedNote(note : Note) : void
    + showNoPinnedNotes() : void
    + showNoNotes() : void
    + showNoteList(notes : List<Note>, isPinned : boolean) : void
    + printLine() : void
    + close() : void
    + showNoNotesFound() : void
    + showFoundNotes(matchedNotes : ArrayList<Note>) : void
    + showJustPinnedNote(note : Note, noteId : String) : void
    + showRepoInit(repoName : String) : void
    + showSuccessfullyTaggedNote(noteId : String, tag : String) : void
    + showSuccessfullyAddedTag(tag : String) : void
    + showOpeningEditor() : void
    + showNoteSavedFromEditor() : void
    + showNoteEdited(updatedNote : Note) : void
    + showSuccessfulLinking(referencingTitle : String, linkedToTitle : String) : void
    + showLinkedNotes(linkedNotes : ArrayList<Note>, noteId : String, listToShow : String) : void
    + showSuccessfullyUnlinkedNotes(sourceNoteId : String, targetNoteId : String) : void
    + showSuccessfullyDoubleLinkedNotes(noteTitle1 : String, noteTitle2 : String) : void
    + showSuccessfullyUnlinkedBothNotes(noteId1 : String, noteId2 : String) : void
    + showTagsSingleNote(tags : List<String>, noteId : String) : void
    + showTagsListGlobal(tags : List<String>) : void
    + showSuccessfullyDeletedTagFromNote(noteId : String, tag : String) : void
    + showSuccessfullyDeletedTag(tag : String) : void
    + showSuccessfullyRenamedTag(oldTag : String, newTag : String) : void
}
@enduml